import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'
import Button from 'src/components/shared/Button'
import Search from 'src/components/shared/Search'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

type HomeProps = {
    locale: string
}

const Home = ({ locale }: HomeProps) => {
    const { t } = useTranslation('common')

    return (
        <div className={styles.container}>
            hello
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Button title="Test Button" />
            <Search handleSearchChange={() => {}} />
        </div>
    )
}

export const getStaticProps = async ({ locale }: { locale: string }) => ({
    props: {
        ...(await serverSideTranslations(locale, ['common', 'shows']))
    }
})

export default Home
