import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'
import { store } from 'store'
import { Provider } from 'react-redux'

const Home: NextPage = () => {
  return (
    <Provider store={store}>
    <div className={styles.container}>
    hello
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
          
</Provider>
  )
}

export default Home
